FirstLabBackend/urls.py
from django.contrib import admin
from django.urls import path, re_path
from test_django import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('favourite_books/<str:user>/', views.favourite_books, name='favourite_books'),
    path('books/', views.book_list, name='books'),
    re_path(r'^profile/(?P<username>[\w.@+-]+)/$', views.profile_dispatcher, name='profile_dispatcher'),
    path('', views.show_index, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home_page, name='home'),
    path('new_review/<int:book_id>/', views.create_review, name='create_review'),
    path('edit_profile/<str:user>/', views.edit_profile, name='edit_profile'),
    path('not_access/', views.access_denied, name='not_access'),
    path('incorrect_login/', views.incorrect_login, name='login_error'),
    path('request/', views.request_form, name='request_form'),
    path('validate_username', views.validate_username, name='validate_username'),
    path('update_heart_icon/', views.update_heart_icon, name='update_heart_icon'),
]

test_django/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django import forms


def validate_number_length(value):
    if len(str(value)) != 4:
        raise forms.ValidationError('Год публикации должен быть четырехзначным числом')


class Reader(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="id читателя",
                             help_text="Выберите id читателя", null=True, blank=True)
    first_name = models.CharField(max_length=50, verbose_name="Имя", help_text="Введите имя", null=False, blank=False)
    last_name = models.CharField(max_length=100, verbose_name="Фамилия", help_text="Введите фамилию",
                                 null=True, blank=True)
    email = models.EmailField(verbose_name='Email')
    date_of_birth = models.DateField(verbose_name='Дата рождения', blank=True, null=True, default=datetime.date.today)

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'Reader'


class Critic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='id критика',
                             help_text="Выберите id критика", null=True, blank=True)
    first_name = models.CharField(max_length=50, verbose_name='Имя', help_text='Введите имя', null=False, blank=False)
    last_name = models.CharField(max_length=100, verbose_name='Фамилия', help_text='Введите фамилию',
                                 null=True, blank=True)
    email = models.EmailField(verbose_name='Email')
    organization = models.CharField(max_length=200, verbose_name='Организация', blank=True, null=True)
    years_of_experience = models.PositiveIntegerField(verbose_name='Стаж работы', blank=True, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'Critic'


class Author(models.Model):
    name = models.CharField(max_length=100, primary_key=True, verbose_name='Имя',
                            help_text='Введите имя автора', null=False, blank=False)
    language = models.CharField(max_length=100, verbose_name='Язык',
                                help_text='Введите язык, который использует автор для своих книг',
                                null=True, blank=True)
    birth_date = models.DateField()
    biography = models.TextField(verbose_name='Об авторе', help_text='Расскажите немного о жизни автора',
                                 null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Author'


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название',
                            help_text='Введите название жанра', null=False, blank=False)
    description = models.TextField(verbose_name='Описание', help_text='Добавьте описание жанра',
                                   null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Genre'


class Book(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название',
                             help_text='Введите название книги', null=False, blank=False)
    author = models.ManyToManyField(Author, verbose_name='Автор', help_text='Выберите автора', blank=False)
    publication_year = models.IntegerField(validators=[validate_number_length], verbose_name='Год публикации',
                                           help_text='Введите год публикации', null=False, blank=False)
    description = models.TextField(verbose_name='Описание', help_text='Добавьте описание книги',
                                   null=False, blank=False)
    genres = models.ManyToManyField(Genre)

    def __str__(self):
        author_names = ", ".join([author.name for author in self.author.all()])
        return f'{self.title} ({author_names})'

    class Meta:
        db_table = 'Book'


class Review(models.Model):
    critic = models.ForeignKey(Critic, on_delete=models.CASCADE, verbose_name='Критик', help_text="Выберите критика",
                               null=False, blank=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='Книга', help_text="Выберите книгу",
                             null=False, blank=False)
    content = models.TextField(verbose_name='Рецензия', help_text="Напишите Вашу рецензию", null=False, blank=False)

    def __str__(self):
        return f'Рецензия от критика {self.critic.user.username} на книгу "{self.book.title}"'

    class Meta:
        db_table = 'Review'


class FavoriteBook(models.Model):
    reader = models.ForeignKey(Reader, on_delete=models.CASCADE, verbose_name="id читателя",
                               help_text="Выберите читателя", null=True, blank=True)
    book = models.ManyToManyField(Book, help_text="Выберите книги")

    def __str__(self):
        return f'Любимые книги читателя {self.reader}'

    class Meta:
        db_table = 'Favourite Book'


class UserRequest(models.Model):
    REQUEST_TYPES = (
        ('A', 'Автор'),
        ('B', 'Книга'),
    )

    request_type = models.CharField(max_length=1, choices=REQUEST_TYPES, verbose_name='Тип заявки')
    author_name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Имя автора')
    book_title = models.CharField(max_length=100, null=True, blank=True, verbose_name='Название книги')

    def __str__(self):
        return f'{self.get_request_type_display()} - {self.author_name} - {self.book_title if self.book_title else ""}'

    class Meta:
        db_table = 'User Request'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'images/favicon-32x32.png' %}" type="image/x-icon">
    {% block additional_css %}
    {% endblock %}
</head>

<header>
    <nav>
        <ul id="menu-bar-template">
            <li {% if request.path_info == '/home/' %} class="active" {% endif %}><a href="{% url 'home' %}">Home</a>
            </li>
            <li {% if request.path_info == '/books/' %} class="active" {% endif %}><a href="{% url 'books' %}">Books</a>
                <!--
                <ul>
                    <li><a href="#">Book Shop</a></li>
                    <li><a href="#">Collectables</a></li>
                </ul>
            -->
            </li>
            <!--
                <li><a href="#">Services</a></li>
                <li><a href="#">About</a></li>
            -->
            <li><a href="{% url 'request_form' %}">Contact Us</a></li>
            <div class="last-items-container">
                <li class="last-item">
                    {% if user.is_authenticated %}
                        <a href="{% url 'profile_dispatcher' user.username %}">Мой профиль</a>
                    {% endif %}
                </li>
                <li class="last-item">
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}">Выйти</a>
                    {% else %}
                        <a href="{% url 'login' %}">Войти</a>
                    {% endif %}
                </li>
            </div>
        </ul>
    </nav>
</header>

<body>
{% block content %}

{% endblock %}
</body>
</html>

templates/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Detail</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block additional_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/book_detail.css' %}">
    {% endblock %}
</head>

<body>
{% block content %}
    <div class="book">
        <div class="main_info">
            <h1>{{ book.title }}</h1>
            <p>{% for author in book.author.all %}{{ author.name }}{% if not forloop.last %},{% endif %}{% endfor %}</p>
        </div>

        <main>
            <p data-before="Год публикации:">{{ book.publication_year }}</p>
            <p data-before="Описание:">{{ book.description }}</p>
            <p data-before="Жанры:">
                {% for genre in book.genres.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        </main>

        <div class="reviews">
            <h3>Рецензии:</h3>
            {% for review in reviews %}
                <div class="quote">
                    <div class="critic_name">
                        <p>{{ review.critic }}:</p>
                    </div>
                    <p>{{ review.content }}</p>

                    {% if user.username == review.critic.user.username and user_belongs_to_critics_group %}
                        <form method="post" class="delete-review-form">
                            {% csrf_token %}
                            <input type="hidden" name="review_id" value="{{ review.id }}">
                            <button type="submit" class="delete-review-btn"><i class="fa-times fa-1x fas"></i></button>
                        </form>
                    {% endif %}

                </div>
            {% empty %}
                <p>Рецензий пока нет.</p>
            {% endfor %}
        </div>
        {% if user_belongs_to_critics_group %}
            <a href="{% url 'create_review' book.id %}" class="button-link">Создать рецензию</a>
        {% endif %}
    </div>
    <script>
        window.onload = function () {
            var buttons = document.querySelectorAll('.delete-review-btn');
            buttons.forEach(function (button) {
                button.addEventListener('mouseover', function () {
                    this.closest('.quote').style.backgroundColor = 'rgba(222, 212, 225, 0.3)';
                });
                button.addEventListener('mouseout', function () {
                    this.closest('.quote').style.backgroundColor = '';
                });
            });
        };
    </script>
{% endblock %}
</body>
</html>

templates/book_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block additional_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/home_page.css' %}">
    {% endblock %}
</head>

<body>
{% block content %}

    <div class="webBody1">
        <ul>
            <div class="book_container">
                {% for book in books %}
                    <div class="book">

                        <div class="main_book_info">
                            <h3>{{ book.title }}</h3>
                            <p>{% for author in book.author.all %}{{ author.name }}{% if not forloop.last %},
                            {% endif %}{% endfor %}</p>
                        </div>

                        <p data-before="Год публикации:">{{ book.publication_year }}</p>
                        <p data-before="Описание:"> {{ book.description }}</p>
                        <p data-before="Жанры:">
                            {% for genre in book.genres.all %}{{ genre.name }}{% if not forloop.last %},
                            {% endif %}{% endfor %}</p>
                        <div class="button-container">
                            <a href="{% url 'book_detail' book_id=book.id %}" class="button-link">Подробнее</a>

                            {% if user_is_reader %}
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="book_id" value="{{ book.id }}">
                                    <button type="submit"
                                            class="{% if book.is_favourite %}heart-icon-2{% else %}add-to-favorites-btn{% endif %}">
                                        <i class="fa-heart fa-3x {% if book.is_favourite %}fas{% else %}far heart-icon{% endif %}"></i>
                                    </button>
                                </form>

                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </ul>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function () {
            $('form').on('submit', function () {
                var form = $(this);
                var bookId = form.find('input[name="book_id"]').val();
                var csrftoken = form.find('input[name="csrfmiddlewaretoken"]').val();

                $.ajax({
                    type: 'POST',
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    data: {'book_id': bookId},
                    url: "{% url 'update_heart_icon' %}",
                    success: function (response) {
                        var heartIcon = form.find('.fa-heart');
                        if (response.is_favorite) {
                            heartIcon.removeClass('far').addClass('fas');
                        } else {
                            heartIcon.removeClass('fas').addClass('far');
                        }
                    },
                    error: function (response) {
                        if (response.responseJSON) {
                            console.log(response.responseJSON.errors);
                        } else {
                            console.log('An error occurred, but no additional information was provided.');
                        }
                    }
                });
                return false;
            });
        });
    </script>
{% endblock %}
</body>
</html>

templates/create_review.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Create Review</title>
    {% load crispy_forms_tags %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/create_review.css' %}">
</head>
<body>
<div class="container">
    <div class="card">
        <h1>Добавить рецензию</h1>
        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                <p>{{ form.critic.label }}: {{ request.user.get_username }}
                    <input type="hidden" name="critic" value="{{ critic.id }}"/></p>
                <p>{{ form.book.label }}: {{ book.title }}
                    <input type="hidden" name="book" value="{{ book.id }}"/></p>
                <p>{{ form.content.label }}: {{ form.content }}</p>
                <button class="submit-button" type="submit">Отправить</button>
            </form>

            {% if form.errors %}
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ field.label }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

templates/critic_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Critic profile</title>
    {% extends 'base.html' %}
    {% load static %}
    {% load filters %}
    {% block additional_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    {% endblock %}
</head>
<body>
{% block content %}
    <div class="container">
        <div class="card">
            <h1>Профиль критика {{ critic.user.username }}</h1>
            <div class="critic-info">
                <div class="critic-info-top">
                    <div class="profile-info-left">
                        <p>Имя: {{ critic.first_name }}</p>
                        <p>Фамилия: {{ critic.last_name|default:"неизвестна" }}</p>
                    </div>

                    <div class="profile-info-right">
                        <p>Email: {{ critic.email }}</p>
                        <p>Организация: {{ critic.organization|default:"неизвестна" }}</p>
                    </div>
                </div>
                <div class="critic-info-bottom">
                    <p>Стаж работы: {{ critic.years_of_experience|russian_plural_form }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редактировать данные</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/edit_profile.css' %}">
</head>
<body>
<div class="container">
    <div class="form-group">
        <h2 class="title">Редактировать данные</h2>
        <div class="form-container" id="profile-form">
            <form method="post" action="{% url 'edit_profile' reader.user.username %}">
                {% csrf_token %}
                <div>
                    <label for="id_first_name">Имя:</label>
                    <input type="text" id="id_first_name" name="first_name" value="{{ reader.first_name }}">
                </div>

                <div>
                    <label for="id_last_name">Фамилия:</label>
                    <input type="text" id="id_last_name" name="last_name" value="{{ reader.last_name }}">
                </div>

                <div>
                    <label for="id_date_of_birth">Дата рождения:</label>
                    <input type="date" id="id_date_of_birth" name="date_of_birth"
                           value="{{ reader.date_of_birth|default_if_none:'' }}">
                </div>

                <div class="button-container">
                    <input class="submit-button" type="submit" value="Сохранить изменения">
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/favourite_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Favourite books</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block additional_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/favourite_books.css' %}">
    {% endblock %}
</head>

<body>
{% block content %}
    {% if favourite_books %}
        <div class="reader">
            {% for favourite_book in favourite_books %}
                <div class="favourite_books">
                    <h2>Любимые книги {{ favourite_book.reader.user }}</h2>
                    <div class="book_container">
                        {% for book in favourite_book.book.all %}
                            <div class="book">
                                <div class="main_book_info">
                                    <h3>{{ book.title }}</h3>
                                    <p>{% for author in book.author.all %}{{ author.name }}{% if not forloop.last %},
                                    {% endif %}{% endfor %}</p>
                                </div>
                                <p data-before="Год публикации:">{{ book.publication_year }}</p>
                                <p data-before="Описание:"> {{ book.description }}</p>
                                <p data-before="Жанры:">
                                    {% for genre in book.genres.all %}{{ genre.name }}{% if not forloop.last %},
                                    {% endif %}{% endfor %}</p>
                                <a href="{% url 'book_detail' book_id=book.id %}" class="button-link">Подробнее</a>
                                <form method="post" class="delete-book-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="book_id" value="{{ book.id }}">
                                    <button type="submit" class="delete-book-btn"><i class="fa-times fa-1x fas"></i>
                                    </button>
                                </form>
                            </div>
                        {% empty %}
                            <p>No favorite books found.</p>
                        {% endfor %}
                    </div>
                </div>
                </div>
            {% endfor %}
    {% else %}
        <div class="else-container">
            <p class="else">Списка любимых книг пока нет</p>
        </div>
    {% endif %}
{% endblock %}
</body>
</html>

templates/home_page.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block additional_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/home_page.css' %}">
    {% endblock %}
</head>

<body>
{% block content %}

    <div class="webBody1">
        <h1> Добро пожаловать в книжный рай </h1>
        <h2>Место, где миры книг сливаются с реальностью</h2>
        <img class="img" src="{% static 'images/book_shelf.png' %}" alt="">

        <div><h2 class="webBody2">Книжный рай – ваш путеводитель по миру уникальных
            историй, где каждая страница является прикосновением к волшебству.
            Погрузитесь в море захватывающих приключений и непревзойденных эмоций,
            выбрав свою идеальную книгу среди нашего огромного ассортимента для взрослых
            и детей!</h2></div>
        <ul>

        </ul>
    </div>
{% endblock %}
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <title> Login and Registration </title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container">
    <input type="checkbox" id="flip">
    <div class="cover">
        <div class="front">
            <img src="{% static 'images/back_img.jpg' %}" alt="">
            <div class="text">
                <span class="text-1">Every new book is a <br> new adventure</span>
            </div>
        </div>
        <div class="back">
            <img class="backImg" src="{% static 'images/back_img.jpg' %}" alt="">
        </div>
    </div>
    <div class="forms">
        <div class="form-content">
            <div class="login-form">
                <div class="title">Sign in</div>
                <form method="post">
                    {% csrf_token %}
                    <div class="input-boxes">
                        <div class="input-box">
                            <i class="fas fa-envelope"></i>
                            <input type="text" id="username" name="username" placeholder="Логин" required>
                            <label for="username" class="visually-hidden">Логин</label>
                        </div>
                        <div class="input-box">
                            <i class="fas fa-lock"></i>
                            <input type="password" id="password" name="password" placeholder="Пароль" required>
                            <label for="password" class="visually-hidden">Пароль</label>
                        </div>
                        <div class="button input-box">
                            <input type="submit" name="login_submit" value="Войти">
                        </div>
                        <div class="text sign-up-text">Ещё нет аккаунта? <label for="flip"><br>Зарегистрируйтесь прямо
                            сейчас!</label></div>
                    </div>

                </form>
            </div>
            <div class="signup-form">
                <div class="title">Sign up</div>
                <form method="post">
                    {% csrf_token %}
                    <div class="input-boxes">
                        <div class="input-box" id="id_username_box">
                            <i class="fas fa-user"></i>
                            <input type="text" id="id_username" name="create_username" placeholder="Логин" required>
                            <label for="id_username" class="visually-hidden">Логин</label>
                        </div>
                        <div class="input-box">
                            <i class="fas fa-envelope"></i>
                            <input type="email" id="email" name="email" placeholder="Почта" required>
                            <label for="email" class="visually-hidden">Почта</label>
                        </div>
                        <div class="input-box">
                            <i class="fas fa-lock"></i>
                            <input type="password" id="create_password" name="create_password" placeholder="Пароль"
                                   required>
                            <label for="create_password" class="visually-hidden">Пароль</label>
                        </div>
                        <div class="button input-box">
                            <input type="submit" name="signup_submit" value="Зарегистрироваться">
                        </div>
                        <div class="text sign-up-text">Уже есть аккаунт? <label for="flip"><br>Просто войдите!</label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    $(document).ready(function () {
        $('#id_username').on('keyup', function () {
            var csrftoken = $('[name=csrfmiddlewaretoken]').val();
            $.ajax({
                headers: {'X-CSRFToken': csrftoken},
                data: {
                    'username': $(this).val(),
                    'csrfmiddlewaretoken': csrftoken
                },
                url: "{% url 'validate_username' %}",
                success: function (response) {
                    if (response.is_taken === true) {
                        $('#id_username').removeClass('is-valid').addClass('is-invalid');
                        $('#usernameError').remove(); // удаляем старое сообщение об ошибке
                        $('#id_username').after('<div class="invalid-feedback d-block" ' +
                            'id="usernameError">Такой логин уже занят</div>');
                        $('input[name="signup_submit"]').prop('disabled', true).addClass('button-disabled');
                    } else {
                        $('#id_username').removeClass('is-invalid').addClass('is-valid');
                        $('#usernameError').remove();
                        $('input[name="signup_submit"]').prop('disabled', false).removeClass('button-disabled'); // включаем кнопку регистрации
                    }
                },
                error: function (response) {
                    console.log(response.responseJSON.errors)
                }
            });
            return false;
        });
    })
</script>
</body>
</html>

templates/login_error.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Сообщение об ошибке</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/errors.css' %}">
</head>
<body>
<div class="login-background"></div>
<div class="login-text-container">
    <p class="login-text">Имя пользователя уже занято, <a href="{% url 'login' %}">
        попробуйте еще раз</a></p>
</div>

<script>
    setTimeout(function () {
        window.location.href = '/';
    }, 10000);
</script>

</body>
</html>

templates/not_access.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Not access</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/errors.css' %}">
</head>
<body>
<div class="access-background"></div>
<div class="access-text-container">
    <p class="access-blinking-text">Нет доступа</p>
</div>
</body>
</html>

templates/reader_profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Reader profile</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block additional_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    {% endblock %}
</head>

<body>
{% block content %}
    <div class="container">
        <div class="card">
            <h1>Профиль {{ reader.user.username }}
                <a class="edit-link" href="{% url 'edit_profile' reader.user.username %}">
                    <i class="fas fa-edit edit-icon"></i>
                </a>
            </h1>

            <div class="reader-info">
                <div class="profile-info-left">
                    <p>Имя: {{ reader.first_name }}</p>
                    <p>Фамилия: {{ reader.last_name }}</p>
                </div>

                <div class="profile-info-right">
                    <p>Email: {{ reader.email }}</p>
                    <p>Дата рождения: {{ reader.date_of_birth|date:"d-m-Y" }}</p>
                </div>
            </div>
            <div>
                <a class="fav-link" href="{% url 'favourite_books' reader.user.username %}">Любимые книги</a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}
</body>
</html>